#!/bin/bash -eux

PROJECT_ROOT="$(cd "$(dirname "$0")/../" && pwd)"
SCRIPTS_DIR=$PROJECT_ROOT/scripts

cd $PROJECT_ROOT

yes yes | swift package --package-path AppCore plugin --allow-writing-to-package-directory --allow-writing-to-directory . sourcery-command --config AppCore/Sources/AppCore/.sourcery.yml
