# name: Snapshot test
# on:
#   pull_request:
#     branches: [ "main" ]
# jobs:
#   build:
#     name: Run snapshot test
#     runs-on: macos-latest-xlarge
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           submodules: recursive
#       - name: Setup Xcode
#         uses: maxim-lobanov/setup-xcode@v1
#         with: 
#           xcode-version: 15.1
#       - name: Set IDESkipPackagePluginFingerprintValidatation
#         run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
#       - name: Xcode cache
#         uses: irgaly/xcode-cache@v1
#         with:
#           key: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
#           restore-keys: xcode-cache-deriveddata-${{ github.workflow }}-
#       - name: Run Xcodebuild Test
#         run: set -o pipefail && xcodebuild test -workspace App.xcworkspace -scheme AppSnapshotTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' -resultBundlePath TestResults.xcresult | xcpretty
#         env:
#           SNAPSHOT_REFERENCE_DIR: ${GITHUB_WORKSPACE}/AppSnapshotTests/__Snapshots__
#       - name: Upload xcresult
#         uses: actions/upload-artifact@v4
#         if: success() || failure()
#         with:
#           name: "TestResults.xcresult"
#           path: "TestResults.xcresult"
#           compression-level: 1

